// Generated by CoffeeScript 1.10.0
(function() {
  var debug, initmodule, loginmodule, paths, phantomcss;

  paths = require('./common/sievo.module-paths');

  phantomcss = require('phantomcss');

  initmodule = require(paths.sievoInit);

  loginmodule = require(paths.sievoLogin);

  debug = require(paths.sievoDebug);

  casper.captureContractsMain = function() {
    return this.waitForResource(/Contracts\/Notification/, function() {
      return phantomcss.screenshot('#contracts-main-wrapper', 'contracts-main-wrapper');
    }, function() {
      return this.test.fail('should see contract management');
    });
  };

  casper.captureContractDetail = function() {
    return this.waitForResource(/Contracts\/Notification/, function() {
      return phantomcss.screenshot('#content', 'contracts #content');
    }, function() {
      return this.test.fail('should see contract management');
    });
  };

  casper.test.begin('contracs visual tests', function(test) {
    initmodule.init();
    loginmodule.login();
    debug.enableClickListener();
    casper.then(function() {
      return casper.click('a[href$=Contracts]');
    });
    casper.then(function() {
      return this.captureContractsMain();
    });
    casper.then(function() {
      return casper.click('#contract0');
    });
    casper.then(function() {
      return this.captureContractDetail();
    });
    casper.then(function() {
      return phantomcss.compareSession();
    });
    return casper.run(function() {
      console.log('\nTHE END.');
      return casper.test.done();
    });
  });

}).call(this);
