// Generated by CoffeeScript 1.10.0
(function() {
  var debug, loginmodule, paths, phantomcss, settings, sievo;

  paths = require('./common/sievo.module-paths');

  phantomcss = require(paths.phantomCss);

  settings = require(paths.sievoSettings);

  loginmodule = require(paths.sievoLogin);

  debug = require(paths.sievoDebug);

  sievo = require(paths.sievoCommon);

  casper.captureBudgetingMain = function() {
    return this.waitForText('Manage budgets', function() {
      return sievo.screenshot('.budgetFrames', 'budget frames');
    }, function() {
      return this.test.fail('should see budget frames');
    });
  };

  casper.captureNewBudgetRound = function() {
    return this.waitForResource(/w*dimensionsToExclude=Time\b/, function() {
      return sievo.screenshot('#new-budgetround-panel', 'new budget round panel');
    }, function() {
      return this.test.fail('ajax request left hanging');
    });
  };

  casper.captureNewFrame = function() {
    return this.waitForText('New budget frame', function() {
      return sievo.screenshot('#new-budgetframe', 'new budget frame');
    }, function() {
      return this.test.fail('New budget frame wont open');
    });
  };

  casper.test.begin('Budgeting visual tests', function(test) {
    settings.init();
    loginmodule.login();
    debug.enableClickListener();
    casper.then(function() {
      return this.click('a[href$=Budgeting]');
    });
    casper.then(function() {
      return this.captureBudgetingMain();
    });
    casper.then(function() {
      return this.click('#label-year-2016 a');
    });
    casper.then(function() {
      return this.captureNewBudgetRound();
    });
    casper.back();
    casper.then(function() {
      return this.click('#round-id-1 a');
    });
    casper.then(function() {
      return this.captureNewFrame();
    });
    casper.then(function() {
      return phantomcss.compareSession();
    });
    return casper.run(function() {
      console.log('\nTHE END.');
      return casper.test.done();
    });
  });

}).call(this);
