// Generated by CoffeeScript 1.10.0
(function() {
  var enableClickListener, enableHttp200Listener, enableHttp404Listener, paths, phantomcss;

  paths = require('./sievo.module-paths');

  phantomcss = require(paths.phantomCss);

  enableClickListener = function() {
    return casper.on('click', function(resource, request) {
      return this.echo("clicked: " + resource);
    });
  };

  enableHttp200Listener = function() {
    return casper.on('http.status.200', function(resource) {
      return this.echo("http 200: " + resource.url);
    });
  };

  enableHttp404Listener = function() {
    return casper.on('http.status.404', function(resource) {
      return this.echo("http 404: " + resource.url);
    });
  };

  exports.enableClickListener = enableClickListener;

  exports.enableHttp200Listener = enableHttp200Listener;

  exports.enableHttp404Listener = enableHttp404Listener;

  exports.enableHttpListeners = function() {
    enableHttp200Listener();
    return enableHttp404Listener();
  };

}).call(this);
