// Generated by CoffeeScript 1.10.0
(function() {
  var paths, phantomcss;

  paths = require('./sievo.module-paths');

  phantomcss = require(paths.phantomCss);

  exports.enableClickListener = function() {
    return casper.on('click', function(resource, request) {
      return this.echo("clicked: " + resource);
    });
  };

}).call(this);
