// Generated by CoffeeScript 1.10.0
(function() {
  var paths, phantomcss, settings;

  paths = require('./sievo.module-paths');

  phantomcss = require(paths.phantomCss);

  settings = require(paths.sievoSettings);

  exports.screenshot = function(selector, name, ignoreSelector) {
    casper.echo('taking screenshot, delay: ' + settings.screenshotDelay);
    return phantomcss.screenshot(selector, settings.screenshotDelay, ignoreSelector, name);
  };

}).call(this);
